"""additional relationships

Revision ID: 16b369ba889c
Revises: 26874d319310
Create Date: 2017-11-01 14:16:42.397584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b369ba889c'
down_revision = '26874d319310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'song', 'albums', ['album_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.drop_column('song', 'album_id')
    # ### end Alembic commands ###
