"""remove label

Revision ID: 26874d319310
Revises: a989049707e0
Create Date: 2017-11-01 13:27:37.005275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26874d319310'
down_revision = 'a989049707e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('label', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
