"""remove producer add label

Revision ID: a989049707e0
Revises: fe99ce14ba44
Create Date: 2017-11-01 12:26:21.873168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a989049707e0'
down_revision = 'fe99ce14ba44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('label', sa.String(length=64), nullable=True))
    op.drop_column('albums', 'producer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('producer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('albums', 'label')
    # ### end Alembic commands ###
