"""add producer migration

Revision ID: fe99ce14ba44
Revises: a5f0a8061150
Create Date: 2017-10-31 13:18:37.161071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe99ce14ba44'
down_revision = 'a5f0a8061150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('producer', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'producer')
    # ### end Alembic commands ###
